import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MonitorSmartphone, ShoppingCart } from 'lucide-react';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col justify-between min-h-screen">
          <header className="fixed flex justify-between items-center shadow-xl bg-white px-20 w-full h-16 z-45">
            <div className="flex items-center gap-3">
              <MonitorSmartphone />
              <Link href="/" className="font-bold text-2xl">
                {' '}
                فروشگاه دیجیتال{' '}
              </Link>
            </div>
            <div>
              <ShoppingCart />
            </div>
          </header>
          <div className="px-20 mt-15">{children}</div>
          <footer className='bg-black w-full text-white flex items-center justify-center h-10'>
            <p>copy: 2025 shcv dev . Allrights reseved</p>
          </footer>
        </main>
      </body>
    </html>
  );
}
